name: OpenG2P Documentation
markdown: kramdown
kramdown:
  input: GFM
  gfm_quirks: [paragraph_end, no_auto_typographic]
  html_to_native: true
  hard_wrap: false
  syntax_highlighter: rouge
  toc_levels: 2..3
incremental: false
permalink: pretty
safe: false
lsi: false
keep_files: []
exclude: ["_scripts", "apidocs/layouts", "Gemfile", "hooks", "index.html", "404.html"]

# TO USE ME:
# jekyll serve --incremental --config _config_authoring.yml

collections:
  samples:
    output: true

plugins:
  - jekyll-redirect-from
  - jekyll-relative-links
  - jekyll-sitemap

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: docs
      toc_min: 2
      toc_max: 3
      tree: true

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _scss
  style:            :compressed
